### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by kcole16** [near/near-explorer#220]
### Overview
Explorer performance is suffering at somewhere over >20k transactions, and is unusable at over >100k. 

We've identified the following steps to improve query performance, especially for transaction queries.

* [x] Extract actions into a separate table (from transactions)
* [x] Test loads, profile query performance
    * [x] Goal: 1M TXs
* [x] Set expectations based on load test results

**Comment by frol** [comment]
Currently, we have synced 1.9M blocks, 15M chunks, and 85k transactions for the testnet (the DB size is only 4GB), and Explorer feels snappy! It seems that we resolved the major bottlenecks with #224 and #231. /cc @icerove 

We still want to know our limits (#219), though.

**Comment by frol** [comment]
There is a sum-up: https://github.com/near/near-explorer/issues/219#issuecomment-613641637

We don't have any outstanding performance issues and so far it seems that our read performance is great and we can handle 10M transactions without breaking a sweat.
