### ISSUE TITLE
Setup new domains (near.org)

### ISSUE THREAD

**Issue by kcole16** [near/near-explorer#271]
### Overview
Setup instances on the new domain (near.org) and permanent redirects from the **explorer.nearprotocol.com** domains to **explorer.near.org**

### TODOs
- [ ] explorer.nearprotocol.com -> explorer.near.org
- [ ] explorer.mainnet.nearprotocol.com -> explorer.mainnet.near.org
- [ ] explorer.testnet.nearprotocol.com -> explorer.testnet.near.org
- [ ] explorer.betanet.nearprotocol.com -> explorer.betanet.near.org
- [ ] explorer.devnet.nearprotocol.com -> explorer.devnet.near.org

**Comment by kcole16** [comment]
@frol Think we'll be safe setting up permanent redirects? Nothing comes to mind that would break

**Comment by frol** [comment]
Yes, we can do this for Explorer.
